const { chromium } = require(process.env.CRAFT_UI_PLAYWRIGHT);
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({headless: true, channel: 'msedge'});
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}, reducedMotion: 'no-preference'});
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const base = process.argv[2];
  const response = await page.request.post(base + '/api/login', {data: {password: 'PASSWORD'}, headers: {'X-CRAFT-CONDUCTOR': '1'}});
  assert.equal(response.status(), 200);
  assert.equal((await page.request.post(base + '/api/auth/change', {data:{mode:'pin',secret:'2468'}, headers:{'X-CRAFT-CONDUCTOR':'1'}})).status(), 200);
  await page.addInitScript(() => { localStorage.setItem('craft-conductor-theme', 'night'); localStorage.setItem('craft-conductor-sounds', 'off'); });
  const shot = async name => {
    if (!process.env.CRAFT_UI_SCREENSHOTS) return;
    fs.mkdirSync(process.env.CRAFT_UI_SCREENSHOTS, {recursive: true});
    await page.waitForFunction(() => !document.querySelector('#toasts .toast:not(.sticky)'));
    await page.screenshot({path: path.join(process.env.CRAFT_UI_SCREENSHOTS, name + '.png')});
  };
  const go = async hash => {
    await page.goto(base + '/#' + hash);
    await page.locator('#app').waitFor({state:'visible'});
    await page.waitForTimeout(600);
  };
  await go('craft-conductor');
  await page.getByRole('button', {name:'Appearance', exact:true}).waitFor();
  assert.equal(await page.locator('.preferences-panel:not(.hidden)').count(), 1);
  await shot('craft-conductor-settings');
  await shot('display');
  await page.evaluate(() => applyTheme('day'));
  await shot('settings-day');
  await page.evaluate(() => applyTheme('night'));
  await page.getByRole('button', {name:'Connections', exact:true}).click();
  await page.getByPlaceholder('Paste your CurseForge API key').fill('unsaved-test-value');
  await page.getByRole('button', {name:'Appearance', exact:true}).click();
  await page.getByRole('button', {name:'Connections', exact:true}).click();
  assert.equal(await page.getByPlaceholder('Paste your CurseForge API key').inputValue(), 'unsaved-test-value');
  await page.getByPlaceholder('Paste your CurseForge API key').fill('');
  await go('s/alpha/settings');
  await page.getByRole('button', {name:'Save settings', exact:true}).waitFor();
  const memory = page.locator('#main input').filter({visible:true});
  await page.evaluate(() => { window.savedMain = document.querySelector('#main').firstElementChild; document.querySelector('#main').scrollTop = 200; });
  const scroll = await page.locator('#main').evaluate(el => el.scrollTop);
  await page.locator('#nav a[href="#help"]').click();
  await page.locator('.help-overlay').waitFor();
  await page.waitForTimeout(350);
  assert.equal(await page.locator('.help-contents .help-toc').count(), 1);
  await shot('help');
  await page.getByRole('button', {name:'User manual', exact:true}).click();
  await page.locator('.help-contents .help-toc li').first().waitFor();
  await page.waitForTimeout(350);
  await shot('manual');
  await page.keyboard.press('Escape');
  await page.locator('.help-overlay').waitFor({state:'detached'});
  assert.equal(await page.evaluate(() => document.querySelector('#main').firstElementChild === window.savedMain), true);
  assert.equal(await page.locator('#main').evaluate(el => el.scrollTop), scroll);
  assert.equal(new URL(page.url()).hash, '#s/alpha/settings');
  await page.locator('#main').evaluate(el => el.scrollTop = 0);
  await shot('settings');
  for (const [view, name] of [['servers','servers'], ['s/alpha/dashboard','dashboard'], ['s/alpha/console','console'], ['s/alpha/players','players'], ['s/alpha/updates','updates'], ['s/alpha/mods','mods'], ['s/alpha/friends','friends'], ['s/alpha/backups','backups'], ['s/alpha/java','java'], ['new','new-server']]) { await go(view); await shot(name); }
  await go('s/alpha/dashboard');
  await page.evaluate(() => openDoctor());
  await page.waitForFunction(() => document.querySelectorAll('.doctor-list li').length > 1);
  await shot('check-my-setup');
  await page.locator('#doctor').getByRole('button', {name:'Close',exact:true}).click();
  await go('s/alpha/players');
  await page.getByRole('heading', {name:'Player activity',exact:true}).scrollIntoViewIfNeeded();
  await shot('player-activity');
  await go('s/alpha/settings');
  await page.getByRole('heading', {name:'Web map',exact:true}).scrollIntoViewIfNeeded();
  await shot('web-map');
  await go('craft-conductor');
  await page.evaluate(() => openRemoteAccess());
  await page.locator('.remote-step').first().waitFor();
  await shot('remote-access');
  await page.locator('#remote').getByRole('button', {name:'Close',exact:true}).click();
  await go('new');
  await page.evaluate(() => openBrowser({target:'setup',loader:'fabric',version:'1.21.1'}));
  await page.locator('.result').first().waitFor();
  await page.waitForTimeout(350);
  await shot('mod-browser');
  await page.keyboard.press('Escape');
  await page.locator('.inpage-browser').waitFor({state:'detached'});
  await page.evaluate(() => {
    setupState.loader = 'fabric'; setupState.minecraft = '1.21.1';
    window.addingDependency = setupAddMod('example-worldgen', 'Example world generation');
  });
  await page.getByRole('button', {name:'Add anyway', exact:true}).click();
  await page.evaluate(() => window.addingDependency);
  assert.equal(await page.evaluate(() => setupState.mods.get('example-worldgen').channel), 'beta');
  assert.equal(await page.evaluate(() => setupState.mods.has('example-library')), true);
  // Exercise the actual backend preview and render it in the world-generation pane.
  const preview = await page.evaluate(async () => {
    const r = await api('/api/hub/preview', {method:'POST', body:{loader:'fabric', minecraft:'1.21.1', mods:['example-worldgen'], channels:{'example-worldgen':'beta'}, seed:'25698412121455', level_type:'minecraft:normal', structures:true, radius:128}});
    return r.id;
  });
  let map;
  for (let i = 0; i < 120; i++) {
    map = await page.evaluate(id => api(`/api/hub/preview?id=${id}`), preview);
    if (map.state === 'done' || map.state === 'failed') break;
    await page.waitForTimeout(250);
  }
  assert.equal(map.state, 'done', JSON.stringify(map));
  assert.ok(map.map, JSON.stringify(map));
  await page.evaluate(m => {
    setupState.loader = 'fabric'; setupState.minecraft = '1.21.1'; setupState.previews = [m];
    openWorldPanel();
  }, map);
  await page.locator('.map-tile').first().waitFor();
  await page.waitForFunction(() => [...document.querySelectorAll('.map-tile')].some(img => img.complete && img.naturalWidth > 0));
  assert.equal(await page.locator('.map-spawn').evaluate(el => Number.isFinite(parseFloat(el.style.left))), true);
  await page.waitForTimeout(400);
  await shot('map-preview');
  await page.keyboard.press('Escape');
  await page.locator('.inpage-browser').waitFor({state:'detached'});
  await go('s/alpha/updates');
  await page.evaluate(() => openReadiness(['1.21.1'], '1.21.1'));
  await page.locator('.ready-row.green').first().waitFor();
  const color = await page.locator('.dotc.green').first().evaluate(el => getComputedStyle(el).backgroundColor);
  assert.equal(color, 'rgb(34, 197, 94)');
  await page.waitForTimeout(400);
  await shot('update-readiness');
  await page.evaluate(() => applyTheme('day'));
  assert.equal(await page.locator('.dotc.green').first().evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(22, 101, 52)');
  await shot('readiness-day');
  await page.evaluate(() => applyTheme('night'));
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:390,height:844});
  await go('craft-conductor');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.evaluate(() => openHelp());
  await page.waitForTimeout(350);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await shot('help-mobile');
  assert.deepEqual(errors, []);
  await browser.close();
})().catch(e => {console.error(e); process.exit(1);});
