name: Suggest an idea
description: Something craft-conductor could do, or do more easily.
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like craft-conductor to do?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why? What would it make easier?
